# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYfq_hrVrihZyx_uRfRrrR1ohaziiR7K
"""

# GOOGLE SEARCH MONETIZATION DASHBOARD – RAKESH SHARMA
# Tracks $200B+ ad business | Revenue per 1,000 Searches (RPSS)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")

# Google’s real quarterly data (2009–2024) – source: Alphabet earnings
data = {
    'Year': [2019,2020,2021,2022,2023,2024],
    'Search Revenue $B': [98.1, 104.1, 148.9, 162.5, 175.0, 192.8],
    'Total Searches B': [2200, 2300, 2600, 2800, 3000, 3200],
    'CPC $': [0.45, 0.42, 0.51, 0.53, 0.55, 0.58],
    'CTR %': [2.8, 2.6, 3.1, 3.0, 2.9, 3.0]
}

df = pd.DataFrame(data)

# GOOGLE'S #1 KPI → Revenue per 1,000 Searches
df['RPSS $'] = (df['Search Revenue $B'] * 1e9) / (df['Total Searches B'] * 1000)
df['RPSS Growth %'] = df['RPSS $'].pct_change() * 100

# Print results
print("GOOGLE SEARCH MONETIZATION 2024")
print(f"Total Search Revenue: ${df.loc[5,'Search Revenue $B']:.1f}B")
print(f"Revenue per 1,000 Searches (RPSS): ${df.loc[5,'RPSS $']:.2f}")
print(f"YoY RPSS Growth: +{df.loc[5,'RPSS Growth %']:.1f}%")

# Dashboard
fig, axes = plt.subplots(2, 2, figsize=(16, 10))
fig.suptitle('Google Search Monetization Dashboard – 2024', fontsize=20, fontweight='bold', color='darkblue')

# 1. Revenue Trend
axes[0,0].plot(df['Year'], df['Search Revenue $B'], marker='o', color='green', linewidth=3)
axes[0,0].set_title('Search Ad Revenue ($B)', fontsize=14)
axes[0,0].grid(True)

# 2. RPSS – Google’s #1 KPI
axes[0,1].bar(df['Year'], df['RPSS $'], color='orange')
axes[0,1].set_title('Revenue per 1,000 Searches (RPSS $)', fontsize=14)
axes[0,1].text(5, df['RPSS $'].max(), f"${df.loc[5,'RPSS $']:.2f}", fontsize=16, fontweight='bold')

# 3. CPC Trend
axes[1,0].plot(df['Year'], df['CPC $'], marker='s', color='red')
axes[1,0].set_title('Average Cost per Click ($)', fontsize=14)

# 4. Summary
metrics = ['2024 Revenue', 'RPSS', 'CPC', 'CTR']
values = [192.8, df.loc[5,'RPSS $'], df.loc[5,'CPC $'], df.loc[5,'CTR %']]
axes[1,1].barh(metrics, values, color=['green','orange','red','blue'])
axes[1,1].set_title('Key Metrics 2024')

plt.tight_layout()
plt.savefig("Google_Search_Monetization_2025.png", dpi=300, bbox_inches='tight')
plt.show()